spring:
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: kslide-server
        version: 1.0.0
        type: SYNC
        instructions: "This server provides a set of tools to create slideshows."
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true